<?php
/**
 * @var $viewModel \Flexor\CMSPageTie\ViewModel\AlternateLinks
 * @var $block \Magento\Framework\View\Element\Template
 */
$viewModel = $block->getData('viewModel');
$alternativeLinks = $viewModel->getAlternativeLinks();
?>
<?php foreach ($alternativeLinks as $alternativeLink) : ?>
    <?php foreach ($alternativeLink as $localeCode => $link) : ?>
        <link rel="alternate" hreflang="<?= $block->escapeHtmlAttr($localeCode) ?>" href="<?= $block->escapeHtmlAttr($link) ?>"/>
    <?php endforeach; ?>
<?php endforeach; ?>
